#!/bin/bash
dateFromServer=$(curl -v --insecure --silent https://google.com/ 2>&1 | grep Date | sed -e 's/< Date: //')
biji=`date +"%Y-%m-%d" -d "$dateFromServer"`
#########################

BURIQ () {
    curl -sS https://raw.githubusercontent.com/paicria/ARM/main/as > /root/tmp
    data=( `cat /root/tmp | grep -E "^### " | awk '{print $2}'` )
    for user in "${data[@]}"
    do
    exp=( `grep -E "^### $user" "/root/tmp" | awk '{print $3}'` )
    d1=(`date -d "$exp" +%s`)
    d2=(`date -d "$biji" +%s`)
    exp2=$(( (d1 - d2) / 86400 ))
    if [[ "$exp2" -le "0" ]]; then
    echo $user > /etc/.$user.ini
    else
    rm -f /etc/.$user.ini > /dev/null 2>&1
    fi
    done
    rm -f /root/tmp
}

MYIP=$(curl -sS ipv4.icanhazip.com)
Name=$(curl -sS https://raw.githubusercontent.com/paicria/ARM/main/as | grep $MYIP | awk '{print $2}')
echo $Name > /usr/local/etc/.$Name.ini
CekOne=$(cat /usr/local/etc/.$Name.ini)

Bloman () {
if [ -f "/etc/.$Name.ini" ]; then
CekTwo=$(cat /etc/.$Name.ini)
    if [ "$CekOne" = "$CekTwo" ]; then
        res="Expired"
    fi
else
res="PERMISSÃO VÁLIDA"
fi
}

PERMISSION () {
    MYIP=$(curl -sS ipv4.icanhazip.com)
    IZIN=$(curl -sS https://raw.githubusercontent.com/paicria/ARM/main/as | awk '{print $4}' | grep $MYIP)
    if [ "$MYIP" = "$IZIN" ]; then
    Bloman
    else
    res="PERMISSÃO INVÁLIDA"
    fi
    BURIQ
}
clear
red='\e[1;31m'
green='\e[0;32m'
NC='\e[0m'
green() { echo -e "\\033[32;1m${*}\\033[0m"; }
red() { echo -e "\\033[31;1m${*}\\033[0m"; }
PERMISSION
if [ -f /home/needupdate ]; then
red "Your script need to update first !"
exit 0
elif [ "$res" = "PERMISSÃO VÁLIDA" ]; then
echo -ne
else
red "PERMISSÃO INVÁLIDA"
exit 0
fi
echo "America/Sao_Paulo" > /etc/timezone
ln -fs /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime > /dev/null 2>&1
dpkg-reconfigure --frontend noninteractive tzdata > /dev/null 2>&1
clear
echo -e "\E[44;1;37m           Painel 4G           \E[0m"
echo ""
echo -e "                \033[1;31mATENCAO"
echo ""
echo -e "\033[1;32mINFORME SEMPRE A MESMA SENHA"
echo -e "\033[1;32mSEMPRE CONFIRME AS QUESTOES COM\033[1;37m Y"
echo ""
echo -e "\033[1;36mINICIANDO INSTALACAO"
echo ""
echo -e "\033[1;33mAGUARDE..."
apt-get update -y > /dev/null 2>&1
apt-get install nano -y > /dev/null 2>&1
echo ""
echo -e "\033[1;36mINSTALANDO O APACHE2\033[0m"
echo ""
echo -e "\033[1;33mAGUARDE..."
apt-get install apache2 -y > /dev/null 2>&1
apt-get install cron curl unzip -y > /dev/null 2>&1
echo ""
echo -e "\033[1;36mINSTALANDO DEPENDENCIAS\033[0m"
echo ""
echo -e "\033[1;33mAGUARDE..."
apt-get install php5 libapache2-mod-php5 php5-mcrypt -y > /dev/null 2>&1
service apache2 restart 
echo ""
echo -e "\033[1;36mINSTALANDO O MySQL\033[0m"
echo ""
echo -e "\033[1;33mAGUARDE..."
sleep 1
apt-get install mysql-server php5-mysql -y </dev/tty
echo ""
clear
echo -e "\033[1;36mINSTALANDO O PHPMYADMIN\033[0m"
echo ""
echo -e "\033[1;31mATENCAO \033[1;33m!!!"
echo ""
echo -e "\033[1;32mSELECIONE A OPCAO \033[1;31mAPACHE2 \033[1;32mCOM A TECLA '\033[1;33mESPACO\033[1;32m'"
echo ""
echo -e "\033[1;32mSELECIONE \033[1;31mYES\033[1;32m NA OPCAO A SEGUIR (\033[1;36mdbconfig-common\033[1;32m)"
echo -e "PARA CONFIGURAR O BANCO DE DADOS"
echo ""
echo -e "\033[1;32mLEMBRE SE INFORME A MESMA SENHA QUANDO SOLICITADO"
echo ""
echo -ne "\033[1;33mEnter, Para Prosseguir!\033[1;37m"; read
apt-get install phpmyadmin -y
php5enmod mcrypt
service apache2 restart
apt-get install libssh2-1-dev libssh2-php -y > /dev/null 2>&1
php -m |grep ssh2
apt-get install php5-curl -y > /dev/null 2>&1
service apache2 restart
clear
echo -e "\033[1;36mFINALIZANDO INSTALACAO\033[0m"
echo ""
echo -e "\033[1;33mAGUARDE..."
echo ""    
cd /var/www/html
wget https://www.dropbox.com/s/llyxq092ddsv8rk/internet4g.zip > /dev/null 2>&1
unzip internet4g.zip > /dev/null 2>&1
chmod 0777 img
cd img
chmod 0777 icone perfil icons
cd /var/www/html
rm -r index.html > /dev/null 2>&1
rm -r internet4g.zip > /dev/null 2>&1
cd 
service apache2 restart
mysql -h localhost -u root -p -e "CREATE DATABASE net"
service apache2 restart
echo ""
tput setaf 7 ;
tput bold ; read -p "Digite sua Senha: " password ; tput sgr0
echo ""
clear
echo "Altere no codigo abaixo SUASENHAAQUI e coloque a senha que utilizou durante a instalacao no lugar de 'SUA_SENHA'"
sleep 5
nano /var/www/html/conexao.php
clear
wget  https://www.dropbox.com/s/oj97ewguww29j9d/net.sql
echo "Digite a senha do PhpMyAdmin"
mysql -h localhost -u root -p net < net.sql
rm net.sql
service apache2 restart
clear
echo "CONCLUIDO"
