#!/bin/bash 

echo "DIGITE A COR ATUAL"; read atual
echo "DIGITE A COR NOVA"; read acor

sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/colors.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/colors.min.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/components.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/components.min.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/bootstrap.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/bootstrap.min.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/bootstrap-extended.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/bootstrap-extended.min.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/themes/bordered-layout.css
sed -i "s;$atual;$cor;g" /var/www/html/app-assets/css/themes/bordered-layout.min.css

echo "NOVA COR ADICIONADA COM SUCESSO!!" 
sleep 4
pweb
