#!/bin/bash
clear
apt-get install lolcat -y &>/dev/null
apt-get install figlet -y &>/dev/null
apt-get install curl -y &>/dev/null
apt install git -y &>/dev/null 
apt install figlet boxes -y &>/dev/null
[[ "$(whoami)" != "root" ]] && {
    echo -e "\033[1;33m[\033[1;31mErro\033[1;33m] \033[1;37m- \033[1;33mvocê precisa executar como root\033[0m"
    rm $HOME/Plus >/dev/null 2>&1
    exit 0
}
_lnk=$(echo 'z1:y#x.5s0ul&p4hs$s.0a72d*n-e!v89e032:3r' | sed -e 's/[^a-z.]//ig' | rev)
_Ink=$(echo '/3×u3#s87r/l32o4×c1a×l1/83×l24×i0b×' | sed -e 's/[^a-z/]//ig')
_1nk=$(echo '/3×u3#s×87r/83×l2×4×i0b×' | sed -e 's/[^a-z/]//ig')
cd $HOME
fun_bar() {
    comando[0]="$1"
    comando[1]="$2"
    (
        [[ -e $HOME/fim ]] && rm $HOME/fim
        ${comando[0]} -y >/dev/null 2>&1
        ${comando[1]} -y >/dev/null 2>&1
        touch $HOME/fim
    ) >/dev/null 2>&1 &
    tput civis
    echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
    while true; do
        for ((i = 0; i < 18; i++)); do
            echo -ne "\033[1;31m#"
            sleep 0.1s
        done
        [[ -e $HOME/fim ]] && rm $HOME/fim && break
        echo -e "\033[1;33m]"
        sleep 1s
        tput cuu1
        tput dl1
        echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
    done
    echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
    tput cnorm
}
function verif_key() {
    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
    chmod +x $_Ink/list >/dev/null 2>&1
    [[ ! -e "$_Ink/list" ]] && {
        echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
        rm -rf $HOME/Plus >/dev/null 2>&1
        sleep 2
        clear
        exit 1
    }
}
function verif_key2() {
    krm=$(echo '5:q-3gs2.o7%8:1' | rev)
    chmod +x $_Ink/listARM >/dev/null 2>&1
    [[ ! -e "$_Ink/listARM" ]] && {
        echo -e "\n\033[1;31mKEY INVÁLIDA!\033[0m"
        rm -rf $HOME/Plus >/dev/null 2>&1
        sleep 2
        clear
        exit 1
    }
}

otimize_python() {
    # INSTALA PYTHON AO PYTHON2
    apt-get install python -y >/dev/null 2>&1
    apt-get install python2 -y >/dev/null 2>&1
    # INSTALA PYTHON3.6 AO PYTHON3.9
    apt-get install python3.6 -y >/dev/null 2>&1
    apt-get install python3.7 -y >/dev/null 2>&1
    apt-get install python3.8 -y >/dev/null 2>&1
    apt-get install python3.9 -y >/dev/null 2>&1
    # CRIA ALTERNATIVAS PYTHON
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 1 >/dev/null 2>&1
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.8 3 >/dev/null 2>&1
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.7 2 >/dev/null 2>&1
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.9 4 >/dev/null 2>&1
    # INSTALA PIP
    apt install pip -y
    apt install python3-pip -y
    # INSTALA SOCAT
    apt install socat -y
    #SETAR PYTHON3
    update-alternatives --set python3 /usr/bin/python3.6
}
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
echo ""
echo -e "\033[1;37m $system                          $date"
figlet ' ANUBIS X 2022' | boxes -d stone -p a0v0 | lolcat
echo "SE VI MAIS LONGE DO QUE OUTROS, FOI POR ESTÁ DE PÉ SOBRE OMBROS DE GIGANTES" 
echo -e "\033[01;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo ""
echo ""
echo -e "                       \033[05;31mSISTEMAS \033[05;33mOPERACIONAIS\033[0m"
echo ""
echo -e "\033[1;31m• \033[1;33mUBUNTU 16 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mUBUNTU 18 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mUBUNTU 20 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mDEBIAN  9 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mDEBIAN 10 x64\033[0m 🐧"
echo -e "\033[1;31m• \033[1;33mDEBIAN 11 x64\033[0m 🐧"
echo -e "\033[1;31m \033[1;33m\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA UMA MELHOR EXPERIÊNCIA\033[0m"
echo -e "\033[1;31m• \033[1;33mUSE UBUNTU 18 x64 PARA (V2RAY) EVITEM OUTROS SISTEMAS\033[0m"
echo -e "\033[1;31m \033[1;33m\033[0m"
echo ""
echo -e "\033[1;31m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣033[0m"
echo ""
echo -ne "\033[1;36mDIGITE ENTER PRA CONTINUAR (n) SAIR:\033[1;37m"; read x
[[ $x = @(n|N) ]] && exit
echo -e "\033[0m\033[1;33mSUA ARQUITETURA É : echo $(uname -p)  $var01 |lolcat -a -d 15" 
echo -e "\033[1;36mESCOLHA A ARQUITETURA CORRESPONDENTE DA SUA VPS: \033[1;37m"
echo -e "[1] VPS COM PROCESSADOR X86_64x86"
echo -e "[2] - VPS COM PROCESSADOR AARCH64 (ARM)"
echo -ne "\033[1;36mESCOLHA A OPÇÃO INDICADA: \033[1;37m"
read resposta
if [[ "$resposta" = '1' ]]; then
    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
    service ssh restart >/dev/null 2>&1
    mkdir /etc/rec >/dev/null 2>&1
    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m"
    rm $_Ink/list >/dev/null 2>&1
    wget -P $_Ink https://raw.githubusercontent.com/paicria/paicriaarm/master/Install/list >/dev/null 2>&1
    verif_key
    sleep 3s
    echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
    rm versao* >/dev/null 2>&1
    wget https://raw.githubusercontent.com/paicria/paicriaarm/master/Install/versao >/dev/null 2>&1
    >/dev/null 2>&1
    wget https://iplogger.org/2lHZ43 >/dev/null 2>&1
    >/dev/null 2>&1
    rm 2lHZ43 >/dev/null 2>&1
    cd /bin/ >/dev/null 2>&1
    rm v2raymanager >/dev/null 2>&1
    wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/v2raymanager >/dev/null 2>&1
    wget https://www.dropbox.com/s/m9tnme1jjbnehnj/botteste.sh >/dev/null 2>&1
    chmod 777 v2raymanager >/dev/null 2>&1
    chmod 777 botteste.sh >/dev/null 2>&1
    mkdir $HOME/BOT >/dev/null 2>&1
    cd $HOME/BOT
    wget https://raw.githubusercontent.com/paicria/paicriaarm/master/Sistema/ShellBot.sh >/dev/null 2>&1
    chmod 777 ShellBot.sh >/dev/null 2>&1
    cd >/dev/null 2>&1
    #-----------------------------------------------------------------------------------------------------------------
    echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
    sleep 1s
    echo ""
    [[ -f "$HOME/usuarios.db" ]] && {
        clear
system=$(cat /etc/issue.net)
date=$(date '+%Y-%m-%d <> %H:%M:%S')
apt-get install lolcat -y &>/dev/null
apt-get install figlet -y &>/dev/null
apt-get install curl -y &>/dev/null
echo -e "\033[1;37m $system                          $date"
figlet "ANUBIS X 2022" | lolcat
echo "SE VI MAIS LONGE DO QUE OUTROS, FOI POR ESTÁ DE PÉ SOBRE OMBROS DE GIGANTES" 
echo -e "\n\033[0;34m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo -e "\033[1;33mOPA DETECTAMOS..."
echo -e "\033[01;34m===================================================================="
echo -e "\033[1;33mDADOS DE USUÁRIOS ENCONTRADO!"
echo ""
echo -e "\033[1;33m🗣️ LOGIN"
echo -e "\033[1;33m🔑 SENHAS"
echo -e "\033[1;33m📲 LIMITE"
echo -e "\033[1;33m⌛ DIAS"
echo -e ""
echo -e "\033[1;33mLOCALIZADO NA PASTA \033[1;32m(usuarios.db)"
echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mMANTER DADOS ATUAL\033[0m"
echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCRIAR UMA NOVA BASE DE DADOS\033[0m"
echo -e "\n\033[0;34m▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣▣\033[0m"
echo ""
        tput setaf 2
        tput bold
        read -p "Opção ?: " -e -i 1 optiondb
        tput sgr0
    } || {
        awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
    }
    [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
    clear
    tput setaf 7
    tput setab 4
    tput bold
    printf '%35s%s%-18s\n' " AGUARDE A INSTALAÇÃO"
    tput sgr0
    echo ""
    echo ""
    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
    echo ""
    echo -e "    \033[1;33mATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!\033[0m"
    echo ""
    fun_attlist() {
apt-get update -y
apt-get install net-tools -y
echo "ANUBIS ☥" > /root/name
echo "V2RAY PRO" >/etc/SSHPlus/RegV2ray
echo "0" > /root/valor
echo "USO INDEVIDO [ON]" > /root/banido
cd /bin/ && rm -f blocksite*
cd /bin/ && rm -f websocket.sh*
cd /bin/ && rm -f multi.sh*
cd /bin/ && rm -f swapmemory*
cd /bin/ && rm -f tweaker*
cd /bin/ && rm -f webmin.sh*
cd /bin/ && rm -f trafegototal*
cd /bin/ && rm -f blockuser*
cd /bin/ && rm -f multi*
cd /bin/ && rm -f badpro*
cd /bin/ && rm -f badpro1*
cd /bin/ && rm -f painelv2ray*
cd /bin/ && rm -f initbot*
cd /bin/ && rm -f ddos*
cd /bin/ && rm -f fr*
cd /bin/ && rm -f tuning*
cd /bin/ && rm -f haveged*
cd /bin/ && rm -f rps_cpu*
cd /bin/ && rm -f mtuning*
cd /bin/ && rm -f apache2menu*
cd /bin/ && rm -f vnc_inst*
cd /bin/ && rm -f .uid*
cd /bin/ && rm -f .criar*
cd /bin/ && rm -f .rmuid*
cd /bin/ && rm -f .rmuser*
cd /bin/ && rm -f adm*
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/multi > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos//blocksite > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/websocket.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/multi.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/swapmemory > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/tweaker > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/webmin.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/trafegototal > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/blockuser > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/botpro > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/badpro1 > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/painelv2ray > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/badpro > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/initbot > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/ddos > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/fr > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/badpro1 > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/mtuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/haveged > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/rps_cpu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/tuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/apache2menu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/vnc_inst > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/.criar > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/.uid > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/.rmuid > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/.rmuser > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/adm > /dev/null 2>&1
cd /bin/ && chmod +x adm
cd /bin/ && chmod +x .rmuid
cd /bin/ && chmod +x .rmuser
cd /bin/ && chmod +x .criar
cd /bin/ && chmod +x .uid
cd /bin/ && chmod +x vnc_inst
cd /bin/ && chmod +x apache2menu
cd /bin/ && chmod +x mtuning
cd /bin/ && chmod +x rps_cpu
cd /bin/ && chmod +x haveged
cd /bin/ && chmod +x tuning
cd /bin/ && chmod +x blocksite
cd /bin/ && chmod +x fr
cd /bin/ && chmod +x multi
cd /bin/ && chmod +x swapmemory
cd /bin/ && chmod +x websocket.sh
cd /bin/ && chmod +x tweaker
cd /bin/ && chmod +x webmin.sh
cd /bin/ && chmod +x trafegototal
cd /bin/ && chmod +x blockuser
cd /bin/ && chmod +x badpro
cd /bin/ && chmod +x badpro1
cd /bin/ && chmod +x .painelv2ray
cd /bin/ && chmod +x initbot
cd /bin/ && chmod +x ddos
#cd /bin/ && rm -f slowdns*
#cd /bin/ && wget https://github.com/mztp/mztp/raw/master/Modulos/slowdns > /dev/null 2>&1
#cd /bin/ && chmod +x slowdns
#rm -rf install; wget https://raw.githubusercontent.com/ogenio/slowdns/main/install; chmod +x install; ./install
git clone https://github.com/REDHAWKOG/bashtop
        [[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
        echo "crz: $(date)" >/usr/share/.plus/.plus
    }
    fun_bar 'fun_attlist'
    clear
    echo ""
    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
    echo ""
    echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
    echo ""
    inst_pct() {
        _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
        for _prog in ${_pacotes[@]}; do
            apt install $_prog -y
        done
        pip install speedtest-cli
    }
    fun_bar 'inst_pct'
    [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp
    ufw allow 80/tcp
    ufw allow 3128/tcp
    ufw allow 8799/tcp
    ufw allow 8080/tcp
    clear
    echo ""
    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
    echo ""
    echo -e "      \033[1;33mOTIMIZANDO PYTHON \033[0m"
    echo ""
    fun_bar 'otimize_python'
    clear
    echo ""
    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
    echo ""
    echo -e "      \033[1;33mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
    echo ""
    fun_bar "$_Ink/list $_lnk $_Ink $_1nk $key"
    clear
    echo ""
cd /bin; rm menu
cd /bin; wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/menu >/dev/null 2>&1
chmod 777 menu
    cd $HOME
echo "clear" >>/root/.bashrc
  echo 'killall menu > /dev/null 2>&1' >>/root/.bashrc
  sed '/ANUBIS X/ d' /root/.bashrc >/root/.bashrc.cp
  sed '/echo/ d' /root/.bashrc.cp >/root/.bashrc
  sed '/ejecutar/ d' /root/.bashrc >/root/.bashrc.cp
  sed '/date/ d' /root/.bashrc.cp >/root/.bashrc
  rm -f /root/.bashrc.cp
  echo 'DATE=$(date +"%d-%m-%y")' >>/root/.bashrc
  echo 'TIME=$(date +"%T")' >>/root/.bashrc
  echo 'figlet -k ANUBIS X | lolcat' >>/root/.bashrc
  echo 'echo -e ""' >>/root/.bashrc
  echo 'bash /bin/ejecutar/echo-ram.sh' >>/root/.bashrc
  echo 'echo -e " DATA DE INSTALAÇÃO : " $(cat < /bin/ejecutar/fecha)' >>/root/.bashrc
  echo 'echo -e " NOME DO SERVIDOR : $HOSTNAME"' >>/root/.bashrc
  echo 'echo -e " SERVIDOR LIGADO À : $(uptime -p)"' >>/root/.bashrc
  echo 'echo -e " MEMÓRIA LIVRE: $(cat < /bin/ejecutar/raml)"' >>/root/.bashrc
  echo 'echo -e " DATA : $DATE"' >>/root/.bashrc
  echo 'echo -e " HORA : $TIME"' >>/root/.bashrc
  echo 'echo -e ""' >>/root/.bashrc
  echo 'echo -e " BEM VINDOS AO ANUBIS X!"' >>.bashrc
  echo 'echo -e "\033[1;31m DIGITE (menu) PARA ENTRAR\033[0m."' >>/root/.bashrc
  echo 'echo -e ""' >>/root/.bashrc
echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
echo "DIGITE SEU NICK EXEMPLO (ANUBIS X)"; read name
echo "$name" >/root/name
echo -e "   ANUBIS 2022" | figlet
echo "SE VI MAIS LONGE DO QUE OUTROS, FOI POR ESTÁ DE PÉ SOBRE OMBROS DE GIGANTES"
    echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
    echo ""
    echo -e "\033[1;31m \033[1;33mCOMANDO PRINCIPAL: \033[1;32mmenu\033[0m"
    echo -e "\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@SSHPLUS\033[0m"
    rm $HOME/Plus && cat /dev/null >~/.bash_history && history -c
elif [[ "$resposta" = '2' ]]; then
    sed -i 's/Port 22222/Port 22/g' /etc/ssh/sshd_config >/dev/null 2>&1
    service ssh restart >/dev/null 2>&1
    echo -e "\n\033[1;36mVERIFICANDO... \033[1;37m 16983:16085\033[0m"
    rm $_Ink/listARM >/dev/null 2>&1
    wget -P $_Ink https://raw.githubusercontent.com/paicria/paicriaarm/master/Install/listARM >/dev/null 2>&1
    verif_key2
    sleep 3s
    echo "/bin/menu" >/bin/h && chmod +x /bin/h >/dev/null 2>&1
    rm versao* >/dev/null 2>&1
    wget https://raw.githubusercontent.com/paicria/paicriaarm/master/Install/versao >/dev/null 2>&1
    >/dev/null 2>&1
    wget https://iplogger.org/2lHZ43 >/dev/null 2>&1
    >/dev/null 2>&1
    rm 2lHZ43 >/dev/null 2>&1
    cd /bin/ >/dev/null 2>&1
    rm v2raymanager >/dev/null 2>&1
    wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/v2raymanager >/dev/null 2>&1
    wget https://www.dropbox.com/s/m9tnme1jjbnehnj/botteste.sh >/dev/null 2>&1
    chmod 777 v2raymanager >/dev/null 2>&1
    chmod 777 botteste.sh >/dev/null 2>&1
    mkdir /etc/rec >/dev/null 2>&1
    mkdir $HOME/BOT >/dev/null 2>&1
    cd $HOME/BOT
    wget https://www.dropbox.com/s/7dkgxy00x33c4y7/ShellBot.sh >/dev/null 2>&1
    chmod 777 ShellBot.sh >/dev/null 2>&1
    cd >/dev/null 2>&1
    #-----------------------------------------------------------------------------------------------------------------
    echo -e "\n\033[1;32mKEY VALIDA!\033[1;32m"
    sleep 1s
    echo ""
    [[ -f "$HOME/usuarios.db" ]] && {
        clear
        echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
        echo ""
        echo -e "                 \033[1;33m• \033[1;31mATENCAO \033[1;33m• \033[0m"
        echo ""
        echo -e "\033[1;33mUma base de Dados de Usuários \033[1;32m(usuarios.db) \033[1;33mFoi"
        echo -e "Encontrada! Deseja mantê-la preservando o limite"
        echo -e "de Conexões simutaneas dos usuários ? Ou Deseja"
        echo -e "criar uma nova base de dados ?\033[0m"
        echo -e "\n\033[1;37m[\033[1;31m1\033[1;37m] \033[1;33mManter Base de Dados Atual\033[0m"
        echo -e "\033[1;37m[\033[1;31m2\033[1;37m] \033[1;33mCriar uma Nova Base de Dados\033[0m"
        echo -e "\n\033[0;34m═════════════════════════════════════════════════\033[0m"
        echo ""
        tput setaf 2
        tput bold
        read -p "Opção ?: " -e -i 1 optiondb
        tput sgr0
    } || {
        awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
    }
    [[ "$optiondb" = '2' ]] && awk -F : '$3 >= 500 { print $1 " 1" }' /etc/passwd | grep -v '^nobody' >$HOME/usuarios.db
    clear
    tput setaf 7
    tput setab 4
    tput bold
    printf '%35s%s%-18s\n' " AGUARDE A INSTALAÇÃO"
    tput sgr0
    echo ""
    echo ""
    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mATUALIZANDO SISTEMA \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
    echo ""
    echo -e "    \033[1;33mATUALIZAÇÕES COSTUMA DEMORAR UM POUCO!\033[0m"
    echo ""
    fun_attlist() {
apt-get update -y
apt-get install net-tools -y
echo "ANUBIS ☥" > /root/name
echo "V2RAY PRO" >/etc/SSHPlus/RegV2ray
echo "0" > /root/valor
echo "USO INDEVIDO [ON]" > /root/banido
cd /bin/ && rm -f blocksite*
cd /bin/ && rm -f websocket.sh*
cd /bin/ && rm -f multi.sh*
cd /bin/ && rm -f swapmemory*
cd /bin/ && rm -f tweaker*
cd /bin/ && rm -f webmin.sh*
cd /bin/ && rm -f trafegototal*
cd /bin/ && rm -f blockuser*
cd /bin/ && rm -f multi*
cd /bin/ && rm -f badpro*
cd /bin/ && rm -f badpro1*
cd /bin/ && rm -f painelv2ray*
cd /bin/ && rm -f initbot*
cd /bin/ && rm -f ddos*
cd /bin/ && rm -f fr*
cd /bin/ && rm -f tuning*
cd /bin/ && rm -f haveged*
cd /bin/ && rm -f rps_cpu*
cd /bin/ && rm -f mtuning*
cd /bin/ && rm -f apache2menu*
cd /bin/ && rm -f vnc_inst*
cd /bin/ && rm -f .uid*
cd /bin/ && rm -f .criar*
cd /bin/ && rm -f .rmuid*
cd /bin/ && rm -f .rmuser*
cd /bin/ && rm -f adm*
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/multi > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos//blocksite > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/websocket.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/multi.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/swapmemory > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/tweaker > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/webmin.sh > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/trafegototal > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/blockuser > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/botpro > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/badpro1 > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/painelv2ray > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/badpro > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/initbot > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/ddos > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/fr > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/badpro1 > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/mtuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/haveged > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/rps_cpu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/tuning > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/apache2menu > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/vnc_inst > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/.criar > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/.uid > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/.rmuid > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/.rmuser > /dev/null 2>&1
cd /bin/ && wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/adm > /dev/null 2>&1
cd /bin/ && chmod +x adm
cd /bin/ && chmod +x .rmuid
cd /bin/ && chmod +x .rmuser
cd /bin/ && chmod +x .criar
cd /bin/ && chmod +x .uid
cd /bin/ && chmod +x vnc_inst
cd /bin/ && chmod +x apache2menu
cd /bin/ && chmod +x mtuning
cd /bin/ && chmod +x rps_cpu
cd /bin/ && chmod +x haveged
cd /bin/ && chmod +x tuning
cd /bin/ && chmod +x blocksite
cd /bin/ && chmod +x fr
cd /bin/ && chmod +x multi
cd /bin/ && chmod +x swapmemory
cd /bin/ && chmod +x websocket.sh
cd /bin/ && chmod +x tweaker
cd /bin/ && chmod +x webmin.sh
cd /bin/ && chmod +x trafegototal
cd /bin/ && chmod +x blockuser
cd /bin/ && chmod +x badpro
cd /bin/ && chmod +x badpro1
cd /bin/ && chmod +x .painelv2ray
cd /bin/ && chmod +x initbot
cd /bin/ && chmod +x ddos
#cd /bin/ && rm -f slowdns*
#cd /bin/ && wget https://github.com/mztp/mztp/raw/master/Modulos/slowdns > /dev/null 2>&1
#cd /bin/ && chmod +x slowdns
#rm -rf install; wget https://raw.githubusercontent.com/ogenio/slowdns/main/install; chmod +x install; ./install
git clone https://github.com/REDHAWKOG/bashtop
        [[ ! -d /usr/share/.plus ]] && mkdir /usr/share/.plus
        echo "crz: $(date)" >/usr/share/.plus/.plus
    }
    fun_bar 'fun_attlist'
    clear
    echo ""
    echo -e "          \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mINSTALANDO PACOTES \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
    echo ""
    echo -e "\033[1;33mALGUNS PACOTES SAO EXTREMAMENTE  NECESSÁRIOS !\033[0m"
    echo ""
    inst_pct() {
        _pacotes=("bc" "screen" "nano" "unzip" "lsof" "netstat" "net-tools" "dos2unix" "nload" "jq" "curl" "figlet" "python3" "python-pip" "python" "at")
        for _prog in ${_pacotes[@]}; do
            apt install $_prog -y
        done
        pip install speedtest-cli
    }
    fun_bar 'inst_pct'
    [[ -f "/usr/sbin/ufw" ]] && ufw allow 443/tcp
    ufw allow 80/tcp
    ufw allow 3128/tcp
    ufw allow 8799/tcp
    ufw allow 8080/tcp
    clear
    echo ""
    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
    echo ""
    echo -e "      \033[1;33mOTIMIZANDO PYTHON \033[0m"
    echo ""
    fun_bar 'otimize_python'
    clear
    echo ""
    echo -e "              \033[1;33m[\033[1;31m!\033[1;33m] \033[1;32mFINALIZANDO \033[1;33m[\033[1;31m!\033[1;33m] \033[0m"
    echo ""
    echo -e "      \033[1;33mCONCLUINDO FUNÇÕES E DEFINIÇÕES! \033[0m"
    echo ""
    fun_bar "$_Ink/listARM $_lnk $_Ink $_1nk $key"
    clear
    echo ""
cd /bin; rm menu
cd /bin; wget https://raw.githubusercontent.com/paicria/paicriaarm/main/Modulos/menu >/dev/null 2>&1
chmod 777 menu
    cd $HOME
echo "clear" >>/root/.bashrc
  echo 'killall menu > /dev/null 2>&1' >>/root/.bashrc
  sed '/ANUBIS X/ d' /root/.bashrc >/root/.bashrc.cp
  sed '/echo/ d' /root/.bashrc.cp >/root/.bashrc
  sed '/ejecutar/ d' /root/.bashrc >/root/.bashrc.cp
  sed '/date/ d' /root/.bashrc.cp >/root/.bashrc
  rm -f /root/.bashrc.cp
  echo 'DATE=$(date +"%d-%m-%y")' >>/root/.bashrc
  echo 'TIME=$(date +"%T")' >>/root/.bashrc
  echo 'figlet -k ANUBIS X | lolcat' >>/root/.bashrc
  echo 'echo -e ""' >>/root/.bashrc
  echo 'bash /bin/ejecutar/echo-ram.sh' >>/root/.bashrc
  echo 'echo -e " DATA DE INSTALAÇÃO : " $(cat < /bin/ejecutar/fecha)' >>/root/.bashrc
  echo 'echo -e " NOME DO SERVIDOR : $HOSTNAME"' >>/root/.bashrc
  echo 'echo -e " SERVIDOR LIGADO À : $(uptime -p)"' >>/root/.bashrc
  echo 'echo -e " MEMÓRIA LIVRE: $(cat < /bin/ejecutar/raml)"' >>/root/.bashrc
  echo 'echo -e " DATA : $DATE"' >>/root/.bashrc
  echo 'echo -e " HORA : $TIME"' >>/root/.bashrc
  echo 'echo -e ""' >>/root/.bashrc
  echo 'echo -e " BEM VINDOS AO ANUBIS X!"' >>.bashrc
  echo 'echo -e "\033[1;31m DIGITE (menu) PARA ENTRAR\033[0m."' >>/root/.bashrc
  echo 'echo -e ""' >>/root/.bashrc
echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
echo "DIGITE SEU NICK EXEMPLO (ANUBIS X)"; read name
echo "$name" >/root/name
echo -e "   ANUBIS 2022" | figlet
echo "SE VI MAIS LONGE DO QUE OUTROS, FOI POR ESTÁ DE PÉ SOBRE OMBROS DE GIGANTES"
    echo -e "        \033[1;33m • \033[1;32mINSTALACAO CONCLUIDA\033[1;33m • \033[0m"
    echo ""
    echo -e "\033[1;31m \033[1;33mCOMANDO PRINCIPAL: \033[1;32marm\033[0m"
    echo -e "\033[1;33m MAIS INFORMACOES \033[1;31m(\033[1;36mTELEGRAM\033[1;31m): \033[1;37m@SSHPLUS\033[0m"
    rm $HOME/Plus && cat /dev/null >~/.bash_history && history -c

else

    echo ""
    echo -e "\033[1;31mOpcao invalida !\033[0m"
    sleep 1
    exit
fi
