#!/bin/bash
clear
figlet   '  BOT TESTE' | boxes -d stone -p a0v0 | lolcat
echo -e "\E[44;1;37m            GERENCIAR BOT TESTE          \E[0m"
    echo ""
    echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mINSTALAR BOT \033[0m"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mATIVAR BOT \033[0m"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mDESATIVAR BOT  \033[0m"
    echo -e "\033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mRETORNAR AO MENU \033[0m"
    echo ""

echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "; read i

   case "$i" in

      1) 
clear
rm -rf BOT
inst-botteste
clear
echo " EXEMPLO" 
echo "┏━━━━━━━━━━━━━━━━━━━━━━━━━━━┓"
echo "┃         •🔹• OLA SEJA BEM VINDO •🔹•           ┃"
echo "┗━━━━━━━━━━━━━━━━━━━━━━━━━━━┛" 
    echo "                      MENSAGEM FINAL         "
    echo ""
    echo -ne "\033[1;32mMENSAGEM DE BOAS VINDAS:\033[1;37m "; read titulo
sed -i "s;OLA SEJA BEM VINDO;$titulo;g" /root/BOT/botssh

    echo -ne "\033[1;32mDESCRIÇÃO OU VALOR DA VENDA (Ex Login R$25,00) :\033[1;37m "; read texto
sed -i "s;Conta SSH R$ 10/Mês;$texto;g" /root/BOT/botssh
clear
    echo -ne "\033[1;32mLINK DO APP :\033[1;37m "; read urlapp
sed -i "s;https://play.google.com/store/apps/details?id=com.ntinjector.pro;$urlapp;g" /root/BOT/botssh
    clear
    echo -ne "\033[1;32mLINK DO CONTATO :\033[1;37m "; read urlcontato
sed -i "s;https://t.me/NT_Injector_Pro;$urlcontato;g" /root/BOT/botssh
    clear
    echo -ne "\033[1;32mLINK COPIA E COLA DO PIX :\033[1;37m "; read urlbanco
sed -i "s;b54bc1c3-c892-4b3a-a7ac-73a46f9eefa3;$urlbanco;g" /root/BOT/botssh
    clear
    echo -ne "\033[1;32mLINK DE PAGAMENTO DO BANCO :\033[1;37m "; read bancot
sed -i "s;https://picpay.me/ntpro/10.0;$bancot;g" /root/BOT/botssh
echo "" 
echo "INICIANDO A FUNÇÃO (REINICIANDO SERVIÇOS) " 
sleep 4
clear
fun_prog ()
{
	comando[0]="$1" 
    ${comando[0]}  > /dev/null 2>&1 & 
	tput civis
	echo -ne "\033[1;32m.\033[1;33m.\033[1;31m. \033[1;32m"
    while [ -d /proc/$! ]
	do
		for i in / - \\ \|
		do
			sleep .1
			echo -ne "\e[1D$i"
		done
	done
	tput cnorm
	echo -e "\e[1DOK"
}
echo -ne "\033[1;33mREINICIANDO OPENSSH "; fun_prog 'service ssh restart'
echo ""
sleep 1
if [[ -e /etc/squid/squid.conf ]]; then
echo -ne "\033[1;33mREINICIANDO SQUID PROXY "; fun_prog 'service squid restart'
echo ""
sleep 1
elif [[ -e /etc/squid3/squid.conf ]]; then
echo -ne "\033[1;33mREINICIANDO SQUID PROXY "; fun_prog 'service squid3 restart'
echo ""
sleep 1
fi
if [[ -e /etc/stunnel/stunnel.conf ]]; then
echo -ne "\033[1;33mREINICIANDO SSL TUNNEL "; fun_prog 'service stunnel4 restart'
echo ""
sleep 1
fi
if [[ -e /etc/init.d/dropbear ]]; then
echo -ne "\033[1;33mREINICIANDO DROPBEAR "; fun_prog 'service dropbear restart'
echo ""
sleep 1
fi
if [[ -e /etc/openvpn/server.conf ]]; then
echo -ne "\033[1;33mREINICIANDO OPENVPN "; fun_prog 'service openvpn restart'
echo ""
sleep 1
fi
if netstat -nltp|grep 'apache2' > /dev/null; then
echo -ne "\033[1;33mREINICIANDO APACHE2 "; fun_prog '/etc/init.d/apache2 restart'
echo ""
sleep 1
fi
/etc/init.d/stunnel4 restart
echo -ne "\033[1;33mREINICIANDO OPENVPN "; fun_prog '/etc/init.d/stunnel4 restart'
echo "" 
echo -e "\033[1;32mSERVICOS REINICIADOS COM SUCESSO!\033[0m"
sleep 2
echo "PREPARANDO A VPS PARA SER REINICIADA" 
sleep 5
echo "" 
echo "APÓS REINICIAR ATIVE O BOT NA OPÇÃO 2" 
sleep 6
echo "" 
echo -e "\033[1;31mREINICIANDO...\033[0m"
shutdown -r now 
         ;;

      2)
clear
        botteste
./zx
         ;;

      3)
clear
        botteste
./zx
         ;;

      0)
         menu
         ;;

      *)
         echo "opcao invalida, tente de novo"
         ;;

   esac
menu
