#!/bin/bash
apt install firewalld -y
clear
figlet   '  FIREWALL' | boxes -d stone -p a0v0 | lolcat
echo -e "\E[44;1;37m            GERENCIAR FIREWALL (PRO)            \E[0m"
    echo ""
    echo -e "\033[1;31m[\033[1;36m01\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA TCP\033[0m"
    echo -e "\033[1;31m[\033[1;36m02\033[1;31m] \033[1;37m• \033[1;33mABRIR PORTA UDP \033[0m"
    echo -e "\033[1;31m[\033[1;36m03\033[1;31m] \033[1;37m• \033[1;33mVER PORTA ABERTA \033[0m"
    echo -e "\033[1;31m[\033[1;36m00\033[1;31m] \033[1;37m• \033[1;33mRETORNAR AO MENU \033[0m"
    echo ""

echo -ne "\033[1;32mO QUE DESEJA FAZER \033[1;33m?\033[1;37m "; read i

   case "$i" in

      1)
         clear
echo -ne "\033[1;32mQUAL DESEJA ABRIR TCP \033[1;33m?\033[1;37m "; read tcp
         firewall-cmd --zone=public --permanent --add-port=$tcp/tcp
firewall-cmd --reload
sleep 3
fr
         ;;

      2)
         clear
echo -ne "\033[1;32mQUAL DESEJA ABRIR UDP \033[1;33m?\033[1;37m "; read udp
         firewall-cmd --zone=public --permanent --add-port=$udp/udp
firewall-cmd --reload
sleep 3
fr
;;

      3)
         clear
         firewall-cmd --zone=public --list-ports
echo "" 
echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
fr
         ;;

      0)
         menu
         ;;

      *)
         echo "opcao invalida, tente de novo"
         ;;

   esac
menu
