#!/bin/bash
fun_bar () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -e /usr/lib/sshplus ]] && rm -rf /bin/menu > /dev/null 2>&1
${comando[0]} -y > /dev/null 2>&1
${comando[1]} -y > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "\033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "\033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
IP=$(cat /etc/IP)
x="ok"
menu ()
{
velocity () {
aguarde () {
comando[0]="$1"
comando[1]="$2"
 (
[[ -e $HOME/fim ]] && rm $HOME/fim
[[ ! -d /etc/SSHPlus ]] && rm -rf /bin/menu
${comando[0]} > /dev/null 2>&1
${comando[1]} > /dev/null 2>&1
touch $HOME/fim
 ) > /dev/null 2>&1 &
 tput civis
echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
while true; do
   for((i=0; i<18; i++)); do
   echo -ne "\033[1;31m#"
   sleep 0.1s
   done
   [[ -e $HOME/fim ]] && rm $HOME/fim && break
   echo -e "\033[1;33m]"
   sleep 1s
   tput cuu1
   tput dl1
   echo -ne "  \033[1;33mAGUARDE \033[1;37m- \033[1;33m["
done
echo -e "\033[1;33m]\033[1;37m -\033[1;32m OK !\033[1;37m"
tput cnorm
}
fun_tst () {
speedtest --share > speed
}
echo ""
echo -e "   \033[1;32mTESTANDO A VELOCIDADE DO SERVIDOR !\033[0m"
echo ""
aguarde 'fun_tst'
echo ""
png=$(cat speed | sed -n '5 p' |awk -F : {'print $NF'})
down=$(cat speed | sed -n '7 p' |awk -F :  {'print $NF'})
upl=$(cat speed | sed -n '9 p' |awk -F :  {'print $NF'})
lnk=$(cat speed | sed -n '10 p' |awk {'print $NF'})
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
echo -e "\033[1;32mPING (LATENCIA):\033[1;37m$png"
echo -e "\033[1;32mDOWNLOAD:\033[1;37m$down"
echo -e "\033[1;32mUPLOAD:\033[1;37m$upl"
echo -e "\033[1;32mLINK: \033[1;36m$lnk\033[0m"
echo -e "\033[0;34m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\033[0m"
rm -rf $HOME/speed
echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
}
#limiter
function limit1 () {
   clear
   echo -e "\n\033[1;32mINICIANDO O LIMITER... \033[0m"
   echo ""
   fun_bar 'screen -dmS limiter limiter' 'sleep 3'
   [[ $(grep -wc "limiter" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   } || {
       sed -i '/limiter/d' /etc/autostart
	   echo -e "ps x | grep 'limiter' | grep -v 'grep' && echo 'ON' || screen -dmS limiter limiter" >> /etc/autostart
   }
   echo -e "\n\033[1;32m  LIMITER ATIVO !\033[0m"
   sleep 3
   menu
}
function limit2 () {
   clear
   echo -e "\033[1;32mPARANDO O LIMITER... \033[0m"
   echo ""
   fun_stplimiter () {
      sleep 1
      screen -r -S "limiter" -X quit
      screen -wipe 1>/dev/null 2>/dev/null
      [[ $(grep -wc "limiter" /etc/autostart) != '0' ]] && {
          sed -i '/limiter/d' /etc/autostart
      }
      sleep 1
   }
   fun_bar 'fun_stplimiter' 'sleep 3'
   echo -e "\n\033[1;31m LIMITER PARADO !\033[0m"
   sleep 3
   menu
}
function limit_ssh () {
[[ $(ps x | grep "limiter"|grep -v grep |wc -l) = '0' ]] && limit1 || limit2
}
#onlineapp
function onapp1 () {
   clear
   echo -e "\n\033[1;32mINICIANDO O ONLINE APP... \033[0m"
   echo ""
   apt install apache2 -y > /dev/null 2>&1
   sed -i "s/Listen 80/Listen 8888/g" /etc/apache2/ports.conf >/dev/null 2>&1
   service apache2 restart
   rm -rf /var/www/html/server >/dev/null 2>&1
   mkdir /var/www/html/server >/dev/null 2>&1
   fun_bar 'screen -dmS onlineapp onlineapp' 'sleep 3'
   [[ $(grep -wc "onlineapp" /etc/autostart) = '0' ]] && {
       echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
   } || {
       sed -i '/onlineapp/d' /etc/autostart
	   echo -e "ps x | grep 'onlineapp' | grep -v 'grep' && echo 'ON' || screen -dmS onlineapp onlineapp" >> /etc/autostart
   }
   IP=$(wget -qO- ipv4.icanhazip.com) >/dev/null 2>&1
   echo -e "\n\033[1;32m  ONLINE APP ATIVO !\033[0m"
   echo -e "\033[1;31m \033[1;33mURL de Usuários Online para usar no App\033[0m"
   echo -e " http://$IP:8888/server/online"
   sleep 10
   menu
}
function onapp2 () {
   clear
   echo -e "\033[1;32mPARANDO O ONLINE APP... \033[0m"
   echo ""
   fun_stponlineapp () {
      sleep 1
      screen -r -S "onlineapp" -X quit
      screen -wipe 1>/dev/null 2>/dev/null
      [[ $(grep -wc "onlineapp" /etc/autostart) != '0' ]] && {
          sed -i '/onlineapp/d' /etc/autostart
      }
      sleep 1
   }
   fun_bar 'fun_stponlineapp' 'sleep 3'
   rm -rf /var/www/html/server >/dev/null 2>&1
   echo -e "\n\033[1;31m ONLINE APP PARADO !\033[0m"
   sleep 3
   menu
}
function onapp_ssh () {
[[ $(ps x | grep "onlineapp"|grep -v grep |wc -l) = '0' ]] && onapp1 || onapp2
}
##
function autoexec () {
   if grep "menu;" /etc/profile > /dev/null; then
      clear
      echo -e "\033[1;32mDESATIVANDO AUTO EXECUÇÃO\033[0m"
      offautmenu () {
         sed -i '/menu;/d' /etc/profile
      }
      echo ""
      fun_bar 'offautmenu'
      echo ""
      echo -e "\033[1;31mAUTO EXECUÇÃO DESATIVADO!\033[0m"
      sleep 1.5s
      menu2
   else
      clear
      echo -e "\033[1;32mATIVANDO AUTO EXECUÇÃO\033[0m"
      autmenu () {
         grep -v "^menu;" /etc/profile > /tmp/tmpass && mv /tmp/tmpass /etc/profile
         echo "menu;" >> /etc/profile
      }
      echo ""
      fun_bar 'autmenu'
      echo ""
      echo -e "\033[1;32mAUTO EXECUÇÃO ATIVADO!\033[0m"
      sleep 1.5s
      menu2
   fi

}
#menu2
menu2 (){
[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m✅") || stsf=$(echo -e "\033[1;31m🚫")
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsbotrev=$(ps x | grep "bot_rev"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsom=$(ps x | grep "shutdown -r 16:00"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
_swap1=$(free -h | grep -i swap | awk {'print $2'})
[[ ! -e /usr/lib/licence ]] && rm -rf /bin > /dev/null 2>&1
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
_onli=$(($_ons + $_onop + $_ondrp))
_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-14s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
_onlin=$(printf '%-5s' "$_onli")
_userexp=$(printf '%-5s' "$_expuser")
_tuser=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
info_ip=$(printf '%-19s' "$meu_ipe")
info_fecha=$(printf '%-16s' "$_fecha")
_fecha=$(printf '%(%D)T')
clear
figlet -p -f slant < /root/name | lolcat
echo -e "\033[01;31m╭══════╮\033[0m"
echo -e "\033[01;31m║\033[05;33;42m🌀 MENU 2 🌀\033[01;31m║\033[0m"
echo -e "\033[01;31m╠══════╯\033[0m" && cat /root/versao
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╮\033[0m"
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                          [ ☥ ANUBIS ULTIMATE ☥]                             \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╣\033[0m"
echo -e "\033[1;32mSISTEMA              |  MEMÓRIA RAM          |  PROCESSADOR "
echo -e "\033[1;31mOS: \033[1;37m$_system   | \033[1;31mTOTAL:\033[1;37m$_ram      | \033[1;31mNUCLEO: \033[1;37m$_core\033[0m"
echo -e "\033[1;31mHORÁRIO: \033[1;37m$_hora    | \033[1;31mEM USO: \033[1;37m$_usor      | \033[1;31mEM USO: \033[1;37m$_usop\033[0m"
echo -e "\033[1;32mDATA:\033[1;37m$info_fecha|\033[1;33m LIGADO: \033[1;37m$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}')        | \033[1;31mMEU IP: \033[1;37m$IP \033[0m"
echo -e "\033[1;31m\033[1;36mBAD-UDP/VPN \033[1;37m $stsu \033[1;37m     | \033[1;36mBOT TELEGRAM $stsbot \033[1;37m      | \033[1;37m\033[1;36mLIMITADOR SSH \033[1;37m$stsl               "
[[ ! -e /tmp/att ]]  && {
    echo -e "\033[1;32mCONECTADOS:\033[1;37m $_onlin    | \033[1;31mVENCIDOS: \033[1;37m$_userexp       | \033[1;33mCRIADOS: \033[1;37m$_tuser\033[0m"
    var01='\033[1;37m•'
} || {
    echo -e "  \033[1;33m[\033[1;31m!\033[1;33m]  \033[1;32mEXISTE UMA ATUALIZACAO DISPONIVEL  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
    var01="\033[1;32m!"
}
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━═━═━═━═━━═━━═━═━═━═━═━═━═━═━╤━═━═━═━═━═━═━═━═━═━═━━═━═━═━═━═━═━╣\033[0m"
echo -e "\033[1;34m[\033[1;37m16 •\033[1;34m]\033[1;37m ➩ \033[1;33mMONITOR APP $stson \033[0;32m"
echo -e "\033[1;34m[\033[1;37m17 •\033[1;34m]\033[1;37m ➩ \033[1;33mBLOQUEAR TORRENT $stsf \033[0;32m"
echo -e "\033[1;34m[\033[1;37m18 •\033[1;34m]\033[1;37m ➩ \033[1;33mLIMITADOR $stsl \033[0;32m"
echo -e "\033[1;34m[\033[1;37m19 •\033[1;34m]\033[1;37m ➩ \033[1;33mBADVPN PRO $stsu \033[0;32m"
echo -e "\033[1;34m[\033[1;37m20 •\033[1;34m]\033[1;37m ➩ \033[1;33mAUTO MENU $autm \033[0;32m"
echo -e "\033[1;34m[\033[1;37m21 •\033[1;34m]\033[1;37m ➩ \033[1;33mBOT TELEGRAM $stsbot \033[0;32m"
echo -e "\033[1;34m[\033[1;37m22 •\033[1;34m]\033[1;37m ➩ \033[1;33mBOT TESTE $stsbotteste \033[0;32m"
echo -e "\033[1;34m[\033[1;37m23 •\033[1;34m]\033[1;37m ➩ \033[1;33mBOT CRÉDITO $stsbotrev\033[1;37m \033[0;32m"
echo -e "\033[1;34m[\033[1;37m24 •\033[1;34m]\033[1;37m ➩ \033[1;33mBLOQUER SITE\033[1;37m \033[0;32m"
echo -e "\033[1;34m[\033[1;37m25 •\033[1;34m]\033[1;37m ➩ \033[1;33mAUTO REINICIAR \033[0;32m"
echo -e "\033[1;34m[\033[1;37m26 •\033[1;34m]\033[1;37m ➩ \033[1;33mSISTEMA AVANÇADO \033[0;32m"
echo -e "\033[1;34m[\033[1;37m27 •\033[1;34m]\033[1;37m ➩ \033[1;33mREINICIAR SISTEMA \033[0;32m"
echo -e "\033[1;34m[\033[1;37m28 •\033[1;34m]\033[1;37m ➩ \033[1;33mREINICIAR SERVIÇOS \033[0;32m"
echo -e "\033[1;34m[\033[1;37m29 •\033[1;34m]\033[1;37m ➩ \033[1;33mMAIS OPÇÕES (DSTV) \033[1;32m\033[0;32m"
echo -e "\033[1;34m[\033[1;37m30 •\033[1;34m]\033[1;37m ➩ \033[1;33mSENHA ROOT \033[0;32m"
echo -e "\033[1;34m[\033[1;37m31 •\033[1;34m]\033[1;37m ➩ \033[1;33mATUALIZAR SCRIPT \033[1;37m"
echo -e "\033[1;34m[\033[1;37m32 •\033[1;34m]\033[1;37m ➩ \033[1;33mREMOVER SCRIPT \033[0;32m"
echo -e "\033[1;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━━═━═━═━═━═━═━━═━═━═━═━═━╝\033[0m"
echo -e "\033[1;31m╚╣\033[5;34;47m║ R ➩ MENU 1 ║ P ➩ MENU 2  ║  V ➩ V2RAY  ║\033[0m"
echo -ne " \033[1;31m╰━━━━━━━━❪\033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : "; read x
case "$x" in
   16)
   clear
   onapp_ssh
   ;;
   17)
   blockt
   ;;
   18)
   clear
   limit_ssh
   ;;
   19)
   clear
   badpro1
   ;;
   20)
   autoexec
   ;;
   21)
   botssh
   ;;
   22)
   botteste.sh
   ;;
   23)
   initbot
   ;;
   24)
   clear
   blocksite
   ;;
   25)
   clear
   echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
                                echo -e "\033[1;31mESSA FUNÇÃO ATIVA REINICIALIZAÇÃO AUTOMÁTICA DA TUA VPS \033[1;33m \033[1;32\033[0m"
   echo -e "\033[1;31M ESCOLHA UM HORÁRIO PARA O DESLIGAMENTO EX: \033[1;33m00:00 \033[1;32\033[0m"
echo -ne "\033[1;32mDIGITE A HORA \033[1;33m\033[1;37m: "
            read escolha
                echo ""
                echo -e "\033[1;31m HORÁRIO VÁLIDO!"
                sleep 4
                clear
   shutdown -r +$escolha
   echo -e ""
   echo -e "\033[1;33mAUTO REBOOT AS $escolha ATIVADO COM SUCESSO \033[0m"
   echo -e ""
   echo -e "\033[1;34m[\033[1;37m01 •\033[1;34m]\033[1;37m > \033[1;33mDESATIVAR REBOOT \033[1;37m\033[0;32m"
   echo -e ""
   echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
   ;;
   1)
   clear
   echo -e "\E[44;1;37m             AUTO REBOOT              \E[0m"
   echo -e "\033[1;31mESSA FUNÇÃO DESATIVA A REINICIALIZAÇÃO AUTOMÁTICA DA TUA VPS \033[1;33m \033[1;32\033[0m"
   echo -e "\033[1;31mO HORÁRIO PRÉ DEFINIDO $escolha SERÁ DESATIVADO \033[1;33m \033[1;32\033[0m"
   shutdown -c
echo -e "\033[1;33mAUTO REBOOT DESATIVADO COM SUCESSO \033[0m"
echo -e ""
   echo -ne "\n\033[1;33mENTER \033[1;33mPARA VOLTAR AO \033[1;33mMENU!\033[0m"; read
   ;;
   26)
   clear
   multi 
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   menu2
   ;;
   27)
   clear
   reiniciarsistema
   ;;
   28)
   clear
   reiniciarservicos
   sleep 3
   ;;
   29)
   clear
   MAIS OPÇÕES 
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   menu2
   ;;
   30)
   clear
   senharoot
   sleep 3
   ;;
   31)
   attscript
   ;;
   32)
   clear
   delscript
   ;;
   r)
   menu
   ;;
   q)
   menu3
   ;;
   0|00)
   echo -e "\033[1;31mSaindo...\033[0m"
   sleep 2
   clear
   exit;
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 2
esac
}
while true $x != "ok"
do
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m◉ " || echo -e "\033[1;31m○ ")
if [[ "$(grep -c "Ubuntu" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f2 /etc/issue.net |awk -F "." '{print $1}')
elif [[ "$(grep -c "Debian" /etc/issue.net)" = "1" ]]; then
system=$(cut -d' ' -f1 /etc/issue.net)
system+=$(echo ' ')
system+=$(cut -d' ' -f3 /etc/issue.net)
else
system=$(cut -d' ' -f1 /etc/issue.net)
fi
_ons=$(ps -x | grep sshd | grep -v root | grep priv | wc -l)
[[ "$(cat /etc/SSHPlus/Exp)" != "" ]] && _expuser=$(cat /etc/SSHPlus/Exp) || _expuser="0"
[[ -e /etc/openvpn/openvpn-status.log ]] && _onop=$(grep -c "10.8.0" /etc/openvpn/openvpn-status.log) || _onop="0"
[[ -e /etc/default/dropbear ]] && _drp=$(ps aux | grep dropbear | grep -v grep | wc -l) _ondrp=$(($_drp - 1)) || _ondrp="0"
_onli=$(($_ons + $_onop + $_ondrp))
_ram=$(printf ' %-9s' "$(free -h | grep -i mem | awk {'print $2'})")
_usor=$(printf '%-8s' "$(free -m | awk 'NR==2{printf "%.2f%%", $3*100/$2 }')")
_usop=$(printf '%-1s' "$(top -bn1 | awk '/Cpu/ { cpu = "" 100 - $8 "%" }; END { print cpu }')")
_core=$(printf '%-1s' "$(grep -c cpu[0-9] /proc/stat)")
_system=$(printf '%-14s' "$system")
_hora=$(printf '%(%H:%M:%S)T')
_onlin=$(printf '%-5s' "$_onli")
_userexp=$(printf '%-5s' "$_expuser")
_tuser=$(awk -F: '$3>=1000 {print $1}' /etc/passwd | grep -v nobody | wc -l)
[[ -e /etc/Plus-torrent ]] && stsf=$(echo -e "\033[1;32m✅") || stsf=$(echo -e "\033[1;31m🚫")
stsbot=$(ps x | grep "bot_plus"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsbotteste=$(ps x | grep "bot_teste"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsbotrev=$(ps x | grep "bot_rev"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsl=$(ps x | grep "limiter"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsu=$(ps x | grep "udpvpn"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stson=$(ps x | grep "onlineapp"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
stsom=$(ps x | grep "shutdown -r 16:00"|grep -v grep > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
autm=$(grep "menu;" /etc/profile > /dev/null && echo -e "\033[1;32m✅" || echo -e "\033[1;31m🚫")
info_ip=$(printf '%-19s' "$meu_ipe")
info_fecha=$(printf '%-16s' "$_fecha")
_fecha=$(printf '%(%D)T')
clear
figlet -p -f slant < /root/name | lolcat
echo -e "\033[01;31m╭══════╮\033[0m"
echo -e "\033[01;31m║\033[05;33;42m🌀 MENU 1 🌀\033[01;31m║\033[0m"
echo -e "\033[01;31m╠══════╯\033[0m" && cat /root/versao
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╮\033[0m"
echo -e "\033[01;31m║\033[1;31m\033[5;34;47m                          [ ☥ ANUBIS ULTIMATE ☥]                             \033[1;33m \033[0m\033[01;31m║"
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━═━═━═━═━═━═━═━━═━═━═━═━═━╣\033[0m"
echo -e "\033[1;31m║\033[1;32mSISTEMA              |  MEMÓRIA RAM          |  PROCESSADOR                   \033[01;31m║"
echo -e "\033[1;31m║OS: \033[1;37m$_system   | \033[1;31mTOTAL:\033[1;37m$_ram      | \033[1;31mNUCLEO: \033[1;37m$_core                      \033[01;31m║"
echo -e "\033[1;31m║HORÁRIO: \033[1;37m$_hora    | \033[1;31mEM USO: \033[1;37m$_usor      | \033[1;31mEM USO: \033[1;37m$_usop                   \033[01;31m║"
echo -e "\033[1;31m║\033[1;32mDATA:\033[1;37m$_fecha        |\033[1;33m LIGADO: \033[1;37m$(uptime | awk -F, '{sub(".*up ",x,$1);print $1}')        | \033[1;31mMEU IP: \033[1;37m$IP\033[01;31m          ║"
echo -e "\033[1;31m║\033[1;36mBAD-UDP/VPN \033[1;37m $stsu \033[1;37m     | \033[1;36mBOT TELEGRAM $stsbot \033[1;37m      | \033[1;37m\033[1;36mLIMITADOR SSH \033[1;37m$stsl               ║"
[[ ! -e /tmp/att ]]  && {
echo -e "\033[1;31m║\033[1;32mCONECTADOS:\033[1;37m $_onlin    | \033[1;31mVENCIDOS: \033[1;37m$_userexp       | \033[1;33mCRIADOS: \033[1;37m$_tuser                     \033[01;31m║"
    var01='\033[1;37m•'
} || {
    echo -e "  \033[1;33m[\033[1;31m!\033[1;33m]  \033[1;32mEXISTE UMA ATUALIZACAO DISPONIVEL  \033[1;33m[\033[1;31m!\033[1;33m]\033[0m"
    var01="\033[1;32m!"
}
echo -e "\033[01;31m╠━═━═━═━═━═━═━═━═━═━═━═━━═━━═━═━═━═━═━═━═━═━╤━═━═━═━═━═━═━═━═━═━═━━═━═━═━═━═━═━╣\033[0m"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m01 •\033[1;34m]\033[1;37m ➩ \033[1;33mCRIAR USUARIO \033[0;32m                    ┃ \033[1;34m[\033[1;37mA •\033[1;34m]\033[1;37m ➩ \033[1;33mALTA PERFORMANCE         \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m02 •\033[1;34m]\033[1;37m ➩ \033[1;33mCRIAR TESTE \033[0;32m                      ┃ \033[1;34m[\033[1;37mB •\033[1;34m]\033[1;37m ➩ \033[1;33mMEMÓRIA VIRTUAL          \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m03 •\033[1;34m]\033[1;37m ➩ \033[1;33mREMOVER USUÁRIO \033[0;32m                  ┃ \033[1;34m[\033[1;37mC •\033[1;34m]\033[1;37m ➩ \033[1;33mWEB MIN                  \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m04 •\033[1;34m]\033[1;37m ➩ \033[1;33mMONITOR ONLINE \033[0;32m                   ┃ \033[1;34m[\033[1;37mD •\033[1;34m]\033[1;37m ➩ \033[1;33mDETALHES DA VPS          \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m05 •\033[1;34m]\033[1;37m ➩ \033[1;33mALTERAR DATA \033[0;32m                     ┃ \033[1;34m[\033[1;37mE •\033[1;34m]\033[1;37m ➩ \033[1;33mTRÁFEGO TOTAL            \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m06 •\033[1;34m]\033[1;37m ➩ \033[1;33mALTERAR LIMITE \033[0;32m                   ┃ \033[1;34m[\033[1;37mF •\033[1;34m]\033[1;37m ➩ \033[1;33mBLOQUEAR USUÁRIOS        \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m07 •\033[1;34m]\033[1;37m ➩ \033[1;33mALTERAR SENHA \033[0;32m                    ┃ \033[1;34m[\033[1;37mG •\033[1;34m]\033[1;37m ➩ \033[1;33mMONITOR TRÁFEGO          \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m08 •\033[1;34m]\033[1;37m ➩ \033[1;33mREMOVER VENCIDOS \033[0;32m                 ┃ \033[1;34m[\033[1;37mH •\033[1;34m]\033[1;37m ➩ \033[1;33mMENU CHECKUSER           \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m09 •\033[1;34m]\033[1;37m ➩ \033[1;33mRELATORIO DE USUÁRIO \033[0;32m             ┃ \033[1;34m[\033[1;37mI •\033[1;34m]\033[1;37m ➩ \033[1;33mPROTEGER SERVIDOR        \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m10 •\033[1;34m]\033[1;37m ➩ \033[1;33mCONEXÕES \033[0;32m                         ╰━━━━━━━━━━━━EXTREME━━━━━━━━━━━━━━━\033[0;31m╣"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m11 •\033[1;34m]\033[1;37m ➩ \033[1;33mSPEED TESTE                                                          \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m12 •\033[1;34m]\033[1;37m ➩ \033[1;33mBANNER                                                               \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m13 •\033[1;34m]\033[1;37m ➩ \033[1;33mTRAFEGO         \033[0;32m                  ╭╼╼╼╼╼╼╼[\033[0;32mMENU DE SINTONIZAÇÃO\033[0m]╼╼╼╼╼\033[0;31m╣"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m14 •\033[1;34m]\033[1;37m ➩ \033[1;33mOTIMIZAR        \033[0;32m                  ╰╼> \033[5;34;47m║T ➩ MENU 3║\033[0m                   \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m15 •\033[1;34m]\033[1;37m ➩ \033[1;33mBACKUP SSH                                                           \033[0;31m║"
echo -e "\033[1;31m║\033[1;34m[\033[1;37m16 •\033[1;34m]\033[1;37m ➩ \033[1;33mUSUÁRIO INDEVIDO                                                     \033[0;31m║"
echo -e "\033[1;31m╠━━═━═━═━═━═━═━═━━═━═━═━═━═━═━═━═━━═━═━═━═━═━━═━═━═━═━━━═━═━═━═━═━═━━═━═━═━═━═━╝\033[0m"
echo -e "\033[1;31m╚╣\033[5;34;47m║ R ➩ MENU 1 ║ P ➩ MENU 2  ║  V ➩ V2RAY  ║\033[0m"
echo -ne " \033[1;31m╰━━━━━━━━❪\033[1;32mESCOLHA OPÇÃO DESEJADA\033[1;33m\033[1;31m\033[1;37m : "; read x

case "$x" in 
   1 | 01)
   clear
   .criar
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   2 | 02)
   clear
   criarteste
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   3 | 03)
   clear
   .rmuser
   sleep 3
   ;;
   4 | 04)
   clear
   sshmonitor
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;      
   5 | 05)
   clear
   mudardata
   sleep 3
   ;;
   6 | 06)
   clear
   alterarlimite
   sleep 3
   ;; 
   7 | 07)
   clear
   alterarsenha
   sleep 3
   ;;
   8 | 08)
   clear
   expcleaner
   echo ""
   sleep 3
   ;;     
   9 | 09)
   clear
   infousers
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   10 | 10)
   clear
   conexao
   ;;
   11)
   clear
   velocity
   ;;
   12)
   clear
   banner
   sleep 3
   ;;
   13)
   clear
   echo -e "\033[1;32mPARA SAIR CLICK CTRL + C\033[1;36m"
   sleep 4
   nload
   ;;
   14)
   clear
   otimizar
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   15)
   userbackup
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   16)
   cat banido
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   a)
   tweaker
   ;;
   b)
   swapmemory
   ;;
   c)
   webmin.sh
   ;;
   d)
   clear
   detalhes
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   e) 
   trafegototal
   ;;
   f) 
   blockuser
   ;;
   h)
   cd bashtop/
   ./bashtop
   ;;
   g)
   apt install nethogs -y
   echo -ne "\n\033[1;31M DIGITE [Q] \033[1;33mpara Sair \033[1;32m!\033[0m"
   sleep 5
   nethogs eth0
   echo -ne "\n\033[1;31mENTER \033[1;33mpara retornar ao \033[1;32mMENU!\033[0m"; read
   ;;
   i)
   limit
   ;;
   p)
   menu2
   ;;
   v)
   v2raymanager
   ;;
   t)
   mtuning
   ;;
أنوبيسوجينيوهاكر)
   .secreto
   ;;
   0 | 00)
   echo -e "\033[1;31mSaindo...\033[0m"
   sleep 2
   clear
   exit;
   ;;
   *)
   echo -e "\n\033[1;31mOpcao invalida !\033[0m"
   sleep 2
esac
done
}
menu
#fim
